"use client";


import { ContentObservatory } from "./content-observatory";
import { buildStrategicReading } from "@/lib/strategic-reading";
import { buildPreviousRange, toIsoDate } from '@/lib/date';
import { BestTimeHeatmap } from "@/components/dashboard/best-time-heatmap";
import type { BestTimeData } from "@/lib/best-time";
import { useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, ArrowRight, ExternalLink, Search, X, FileText } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { PLATFORM_LABELS } from '@/lib/types';
import { extraChannelMetrics, buildDrivers, channelChange, comparisonIssue, filterReviewPosts, metricChange, REVIEW_LABELS, reviewNumber as n, type ReviewChannel, type ReviewMetric, type ReviewPost, type ReviewRow } from '@/lib/monthly-review';
import type { JumpStartScore } from '@/lib/scoring';

type Props = { bestTimes?: BestTimeData[]; period: string; previousPeriod: string; from: string; to: string; channels: ReviewChannel[]; posts: ReviewPost[]; rows: ReviewRow[]; previousRows: ReviewRow[]; score: JumpStartScore | null; sources: React.ReactNode; header: React.ReactNode };
const metrics: ReviewMetric[] = ['views','engagements','followers','posts_count'];
const tabs = [{id:'bilan',label:'Bilan du mois'}, {id:'contenus',label:'Explorer les contenus'}, {id:'production',label:'Formats & cadence'}, {id:'conseils',label:'Conseils'}, {id:'horaires',label:'Quand publier'}, {id:'sources',label:'Sources & méthode'}] as const;
const signed = (v: number | null) => v == null ? '—' : `${v>0?'+':''}${n(v)}`;
const date = (value: string) => value ? new Date(value).toLocaleDateString('fr-FR',{day:'numeric',month:'short'}) : 'Date non disponible';
function Change({value}:{value:number|null}) { return <span className={`review-change ${value==null?'':value>0?'positive':value<0?'negative':''}`}>{value!=null && value!==0 && (value>0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>)}{value==null?'Non comparable':`${signed(Math.round(value*10)/10)} %`}</span>; }
function sumOrNull(values: (number|null)[]) { const known=values.filter((v):v is number=>v!=null);return known.length?known.reduce((s,v)=>s+v,0):null; }
function PostImage({post}:{post:ReviewPost}) {
  const [failed,setFailed]=useState<string[]>([]);
  const source=(post.previewCandidates??(post.thumbnail?[post.thumbnail]:[])).find(url=>!failed.includes(url));
  return source ? <img src={source} alt={`Aperçu : ${post.caption.slice(0,80)||post.format}`} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(previous=>[...previous,source])} className="review-thumbnail"/> : <div className="review-preview-unavailable"><FileText size={24} aria-hidden="true"/><span>{post.format==='Texte'?'Publication texte':'Aperçu indisponible'}</span></div>;
}

export function MonthlyWorkspace(p:Props) {
  const [tab,setTab]=useState<string>('bilan');const [metric,setMetric]=useState<ReviewMetric>('engagements');
  const [query,setQuery]=useState('');const [platform,setPlatform]=useState('all');const [format,setFormat]=useState('all');const [sort,setSort]=useState('engagements');const [limit,setLimit]=useState(20);
  const [detail,setDetail]=useState<ReviewPost|null>(null);const [compared,setCompared]=useState<string[]>([]);const [compareOpen,setCompareOpen]=useState(false);
  const totalChanges = metrics.map(key=>{const changes=p.channels.map(c=>channelChange(c,key));return {key,...metricChange(sumOrNull(changes.map(c=>c.current)),sumOrNull(changes.map(c=>c.previous)))};});
  const drivers=buildDrivers(p.channels,metric);const current=totalChanges.find(d=>d.key===metric)!;
  const strategicSignals=useMemo(()=>buildStrategicReading(p.posts),[p.posts]);
  const filtered=useMemo(()=>filterReviewPosts(p.posts,query,platform,format,sort),[p.posts,query,platform,format,sort]);
  const comparison=p.posts.filter(post=>compared.includes(post.id));const compareError=comparisonIssue(comparison);
  const measured=p.posts.filter(post=>post.engagements!=null).length;
  const measuredVisibility=p.posts.filter(post=>post.visibility!=null).length;
  const partial=p.channels.some(c=>c.coverage<80||c.previousCoverage<80);
  const chart=useMemo(()=>{
    const group=(rows:ReviewRow[],key:ReviewMetric)=>{const days=new Map<string,number[]>();for(const r of rows){const value=key==='posts_count'?null:r[key];if(value!=null)days.set(r.date,[...(days.get(r.date)??[]),value]);}return [...days].sort(([a],[b])=>a.localeCompare(b)).map(([day,values])=>({day,value:sumOrNull(values)}));};
    if(metric==='posts_count'){const days=new Map<string,number>();for(const post of p.posts){const day=post.date.slice(0,10);if(day)days.set(day,(days.get(day)??0)+1);}return [...days].sort(([a],[b])=>a.localeCompare(b)).map(([day,value])=>({day,value,previous:null}));}
    const currentByDate=new Map(group(p.rows,metric).map(r=>[r.day,r.value]));const previous=new Map(group(p.previousRows,metric).map(r=>[r.day,r.value]));
    const priorRange=buildPreviousRange({start:new Date(p.from+'T12:00:00'),end:new Date(p.to+'T12:00:00')});
    const start=new Date(p.from+'T12:00:00Z');const end=new Date(p.to+'T12:00:00Z');const days=[];
    for(let d=new Date(start),i=0;d<=end&&i<370;d.setUTCDate(d.getUTCDate()+1),i++){const day=d.toISOString().slice(0,10);days.push({day,value:currentByDate.get(day)??null,previous:(()=>{const priorDay=new Date(priorRange.start);priorDay.setDate(priorDay.getDate()+i);return priorDay<=priorRange.end?previous.get(toIsoDate(priorDay))??null:null;})()});}return days;
  },[p.rows,p.previousRows,p.posts,p.from,p.to,metric]);
  const drill=(network:string)=>{setPlatform(network);setQuery('');setFormat('all');setLimit(20);setTab('contenus');};
  return <div className="review-app">
    {p.header}
    <nav className="review-tabs" aria-label="Espace de bilan mensuel">{tabs.map(t=><button key={t.id} type="button" aria-current={tab===t.id?'page':undefined} onClick={()=>setTab(t.id)}>{t.label}</button>)}</nav>
    {tab==='bilan'&&<div className="review-panel">
      <div className="review-period"><div><span className="review-eyebrow">Résultats consolidés</span><h2>{p.period}</h2><p>Comparaison : {p.previousPeriod}</p></div>{p.score&&<button type="button" className="review-score" onClick={()=>setTab('sources')}><strong>{p.score.global}</strong><span>Score JumpStart<small>sur 100 · voir la méthode</small></span></button>}</div>
      {partial&&<p className="review-notice">Des relevés manquent sur l’une des périodes. Consultez la couverture par réseau avant d’interpréter les écarts.</p>}
      <div className="review-kpis">{totalChanges.map(d=><button key={d.key} className={metric===d.key?'active':''} onClick={()=>setMetric(d.key)} aria-pressed={metric===d.key}><span>{REVIEW_LABELS[d.key]}</span><strong>{n(d.current)}</strong><div><Change value={d.percent}/><small>vs {n(d.previous)}</small></div><small>{signed(d.difference)} {d.key==='followers'?'abonnés':REVIEW_LABELS[d.key].toLowerCase()} sur la période</small></button>)}</div>
      <div className="review-analysis-grid">
        <section className="review-chart" aria-label="Évolution quotidienne"><div className="review-section-title"><div><h3>{REVIEW_LABELS[metric]} jour par jour</h3><p>{metric==='posts_count'?'Publications présentes dans la bibliothèque.':'Trait violet : période choisie · pointillés : période précédente, alignée par jour.'}</p></div></div>
          {chart.length?<div className="review-chart-frame"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{top:15,right:12,left:0,bottom:0}}><CartesianGrid vertical={false} stroke="#eeeaf2"/><XAxis dataKey="day" tickFormatter={v=>date(v)} minTickGap={40} tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis width={55} tickFormatter={v=>new Intl.NumberFormat('fr-FR',{notation:'compact'}).format(v)} tick={{fontSize:11}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>date(String(v))} formatter={(v:number,name:string)=>[n(v),name==='value'?'Période choisie':'Période précédente']}/><Area type="linear" dataKey="previous" stroke="#aaa3b6" strokeDasharray="4 4" fill="transparent" isAnimationActive={false} connectNulls={false}/><Area type="linear" dataKey="value" stroke="#7137ce" strokeWidth={2} fill="#7137ce" fillOpacity={.07} isAnimationActive={false} connectNulls={false}/></AreaChart></ResponsiveContainer></div>:<p className="review-empty">Aucun relevé disponible.</p>}
          <details><summary>Consulter les valeurs du graphique</summary><div className="review-table-scroll" tabIndex={0}><table><thead><tr><th>Date</th><th>{REVIEW_LABELS[metric]}</th><th>Précédent</th></tr></thead><tbody>{chart.map(r=><tr key={r.day}><td>{date(r.day)}</td><td>{n(r.value)}</td><td>{n(r.previous)}</td></tr>)}</tbody></table></div></details>
        </section>
        <section className="review-drivers"><span className="review-eyebrow">Décomposition de l’écart</span><h3>{current.difference==null?'Comparaison indisponible':`${signed(current.difference)} ${REVIEW_LABELS[metric].toLowerCase()}`}</h3><p>La contribution de chaque réseau à cette variation.</p>{drivers.map(d=><button key={d.platform} onClick={()=>drill(d.platform)}><div><strong>{d.label}</strong><b className={(d.difference??0)<0?'negative':'positive'}>{signed(d.difference)}</b></div><span className="review-driver-track"><i style={{width:`${Math.max(2,Math.abs(d.difference??0)/Math.max(1,...drivers.map(x=>Math.abs(x.difference??0)))*100)}%`,background:(d.difference??0)<0?'#b66669':'#7137ce'}}/></span><small>{n(d.previous)} → {n(d.current)} <ArrowRight size={12}/></small></button>)}<small>Ces écarts expliquent le total, pas les causes des résultats.</small></section>
      </div>
      <section><div className="review-section-title"><div><h3>Le bilan par réseau</h3><p>Résultats du compte sur la période. Ouvrez un réseau pour examiner ses contenus.</p></div><button className="review-text-button" onClick={()=>setTab('sources')}>Vérifier les sources <ArrowRight size={14}/></button></div><div className="review-table-scroll" tabIndex={0}><table><thead><tr><th>Réseau</th>{metrics.map(m=><th key={m}>{REVIEW_LABELS[m]}</th>)}<th>Collecte actuelle / précédente</th></tr></thead><tbody>{p.channels.map(c=><tr key={c.platform}><th><button className="review-text-button" onClick={()=>drill(c.platform)}>{PLATFORM_LABELS[c.platform]} <ArrowRight size={14}/></button></th>{metrics.map(m=>{const d=channelChange(c,m);return <td key={m}><strong>{n(d.current)}</strong><small><Change value={d.percent}/></small></td>;})}<td>{c.coverage}% / {c.previousCoverage}%</td></tr>)}</tbody></table></div></section>

      {p.channels.some(c=>extraChannelMetrics(c).length>0)&&<details className="review-format-details"><summary>Statistiques complémentaires par réseau</summary><p className="review-small">Portée, impressions et durée de visionnage disponibles. Ces indicateurs gardent leur définition ; ils ne sont pas additionnés aux vues.</p><div className="review-table-scroll"><table><thead><tr><th>Réseau</th><th>Indicateur</th><th>Période</th><th>Précédente</th><th>Évolution</th></tr></thead><tbody>{p.channels.flatMap(c=>extraChannelMetrics(c).map(item=><tr key={`${c.platform}-${item.label}`}><th>{PLATFORM_LABELS[c.platform]}</th><td>{item.label}</td><td>{n(item.value)}</td><td>{c.hasPrevious?n(item.previous):'—'}</td><td><Change value={metricChange(item.value,c.hasPrevious?item.previous:null).percent}/></td></tr>))}</tbody></table></div></details>}
      <div className="review-next"><div><h3>Les contenus derrière les résultats</h3><p>{p.posts.length} publications collectées · {measured} avec interactions · {measuredVisibility} avec visibilité mesurée.</p></div><button className="review-primary" onClick={()=>setTab('contenus')}>Explorer les contenus <ArrowRight size={16}/></button></div>
    </div>}
    {tab==='contenus'&&<div className="review-panel">
      <div className="review-section-title"><div><h2>Les contenus du mois</h2><p>Explorez les statistiques détaillées et comparez les publications du même compte.</p></div></div>
      <div className="review-content-filters"><label className="review-search"><Search size={17}/><input aria-label="Rechercher dans les publications" placeholder="Un sujet, un produit, une campagne…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(20);}}/></label><select aria-label="Réseau des contenus" value={platform} onChange={e=>{setPlatform(e.target.value);setLimit(20);}}><option value="all">Tous les réseaux</option>{p.channels.map(c=><option key={c.platform} value={c.platform}>{PLATFORM_LABELS[c.platform]}</option>)}</select><select aria-label="Format des contenus" value={format} onChange={e=>{setFormat(e.target.value);setLimit(20);}}><option value="all">Tous les formats</option>{[...new Set(p.posts.map(p=>p.format))].map(f=><option key={f}>{f}</option>)}</select><select aria-label="Trier les contenus" value={sort} onChange={e=>setSort(e.target.value)}><option value="engagements">Interactions décroissantes</option><option value="date">Plus récents</option><option value="visibility">Visibilité décroissante</option></select></div>
      <p className="review-small">{filtered.length} résultat{filtered.length>1?'s':''}. Les statistiques des contenus sont des cumuls à la collecte ; elles ne s’additionnent pas aux statistiques des comptes.</p>
      {compared.length>0&&<div className="review-comparison-bar"><span>{compared.length}/3 contenus à comparer</span><button className="review-primary" onClick={()=>setCompareOpen(true)} disabled={compared.length<2}>Comparer</button><button aria-label="Effacer la comparaison" onClick={()=>setCompared([])}><X size={16}/></button></div>}
      <div className="review-post-list">{filtered.slice(0,limit).map(post=><article key={post.id}><div className="review-post-image"><PostImage post={post}/></div><div className="review-post-copy"><div className="review-post-meta">{PLATFORM_LABELS[post.platform]} <span>· {date(post.date)} · {post.format}</span></div><button className="review-post-title" onClick={()=>setDetail(post)}>{post.caption||'Publication sans légende'}</button><div className="review-post-numbers"><span><b>{n(post.engagements)}</b> interactions</span><span>{post.visibility==null?'Visibilité non disponible':<><b>{n(post.visibility)}</b> {post.visibilityLabel.toLowerCase()}</>}</span>{post.comments!=null&&<span><b>{n(post.comments)}</b> commentaires</span>}{post.shares!=null&&<span><b>{n(post.shares)}</b> partages</span>}</div></div><div className="review-post-actions"><label><input type="checkbox" checked={compared.includes(post.id)} disabled={!compared.includes(post.id)&&compared.length>=3} onChange={()=>setCompared(ids=>ids.includes(post.id)?ids.filter(id=>id!==post.id):[...ids,post.id])}/> Comparer</label><button className="review-text-button" onClick={()=>setDetail(post)}>Statistiques <ArrowRight size={14}/></button></div></article>)}</div>
      {!filtered.length&&<div className="review-empty"><h3>Aucun contenu pour ces critères</h3><button className="review-text-button" onClick={()=>{setQuery('');setPlatform('all');setFormat('all');}}>Effacer les filtres</button></div>}
      {filtered.length>limit&&<button className="review-secondary" onClick={()=>setLimit(l=>l+20)}>Afficher 20 contenus supplémentaires</button>}


    </div>}
    {tab==='conseils'&&<div className="review-panel">      <section className="review-strategy"><div className="review-section-title"><div><span className="review-eyebrow">Du résultat au prochain brief</span><h2>Conseils pour vos prochains contenus</h2><p>Une proposition de contenu par réseau, avec un angle et un déroulé à préparer avec votre équipe JumpStart.</p></div></div>{strategicSignals.length?<div className="review-signal-grid">{strategicSignals.map(signal=><article key={`${signal.platform}-${signal.title}`}><span className="review-eyebrow">{PLATFORM_LABELS[signal.platform]}</span><h3>{signal.title}</h3><p className="review-signal-proof">{signal.observation}</p><div className="review-advice-action"><h4>{signal.format}</h4><p><strong>L’angle : </strong>{signal.angle}</p><ol className="review-advice-steps">{signal.steps?.map((step,index)=><li key={index}>{step}</li>)}</ol><p className="review-small mt-3"><strong>À mesurer. </strong>{signal.measure}</p></div><button className="review-text-button" onClick={()=>setDetail(p.posts.find(post=>post.id===signal.postId)??null)}>Voir le contenu et ses chiffres <ArrowRight size={14}/></button></article>)}</div>:<p className="review-small">Les données de cette sélection ne suffisent pas à distinguer un contenu parmi au moins trois publications du même compte et du même format. Explorez les contenus pour préparer une lecture avec l’agence.</p>}</section><p className="review-notice">Ces recommandations reposent sur les résultats collectés de vos publications. Les compteurs ne révèlent ni le sentiment des commentaires, ni les ventes générées, ni les causes d’une variation. Votre équipe JumpStart complète cette lecture avec le contexte des campagnes et vos objectifs.</p></div>}
    {tab==='production'&&<ContentObservatory posts={p.posts} from={p.from} to={p.to} onOpen={setDetail}/>}
    {tab==='horaires'&&<div className="review-panel">      <section className="space-y-5" aria-label="Meilleur moment pour publier"><div className="review-section-title"><div><h3>Meilleur moment pour publier</h3><p>Vos créneaux observés, réseau par réseau, en heure de Paris.</p></div></div>{(p.bestTimes??[]).map(data=><BestTimeHeatmap key={data.platforms.join('-')} data={data}/>)}{!(p.bestTimes??[]).length&&<p className="review-empty">Pas encore assez de données pour comparer les horaires sur ce périmètre. Il faut au moins 5 publications mesurées, réparties sur 3 créneaux, avec des résultats non nuls.</p>}</section></div>}
    {tab==='sources'&&<div className="review-panel"><div className="review-section-title"><div><h2>Sources & méthode</h2><p>Ce qui est collecté, ce qui manque et ce que l’on peut comparer.</p></div></div><div className="review-notice">Une métrique indisponible n’est pas remplacée par un chiffre inventé. Les vues, impressions et portées gardent leur propre libellé. Les audiences ne sont pas dédupliquées entre réseaux.</div>{p.sources}{p.score&&<details><summary>Calcul du score JumpStart · {p.score.global}/100</summary><p className="review-small">Indice interne conservé : croissance 25 %, portée 25 %, engagement 25 %, régularité 15 %, momentum 10 %. Ce n’est pas un benchmark sectoriel. Les différences de périmètre ou de collecte limitent sa comparaison.</p></details>}</div>}
    <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="review-dialog">{detail&&<><DialogTitle>Statistiques de la publication</DialogTitle><DialogDescription>{PLATFORM_LABELS[detail.platform]} · {date(detail.date)} · {detail.format} · cumuls à la collecte</DialogDescription><div className="review-detail-content"><PostImage post={detail}/><p>{detail.caption||'Publication sans légende'}</p></div><div className="review-detail-metrics">{[{label:'Interactions',value:detail.engagements},{label:detail.visibilityLabel,value:detail.visibility}, {label:'Mentions J’aime',value:detail.likes},{label:'Commentaires',value:detail.comments},{label:'Partages',value:detail.shares},{label:'Enregistrements',value:detail.saves}].filter(m=>m.value!=null).map(m=><div key={m.label}><small>{m.label}</small><strong>{n(m.value)}</strong></div>)}</div>{detail.visibility==null&&<p className="review-small">Visibilité non disponible pour ce contenu. Le ratio d’interactions ne peut pas être calculé.</p>}<div className="review-actions">{detail.url&&<a href={detail.url} target="_blank" rel="noreferrer" className="review-secondary">Voir l’original <ExternalLink size={15}/></a>}</div></>}</DialogContent></Dialog>
    <Dialog open={compareOpen} onOpenChange={setCompareOpen}><DialogContent className="review-dialog"><DialogTitle>Comparer les contenus</DialogTitle><DialogDescription>Même réseau et même compte ; l’âge des contenus et leur diffusion peuvent différer.</DialogDescription>{compareError?<p className="review-notice">{compareError}</p>:<div className="review-table-scroll"><table><thead><tr><th>Mesure</th>{comparison.map(post=><th key={post.id}>{post.caption.slice(0,65)||'Publication'}<small>{date(post.date)} · {post.format}</small></th>)}</tr></thead><tbody>{(['engagements','comments','shares','saves'] as const).map(key=><tr key={key}><th>{{engagements:'Interactions',comments:'Commentaires',shares:'Partages',saves:'Enregistrements'}[key]}</th>{comparison.map(post=><td key={post.id}>{n(post[key])}</td>)}</tr>)}<tr><th>Visibilité</th>{comparison.map(post=><td key={post.id}>{post.visibility==null?'Indisponible':`${n(post.visibility)} ${post.visibilityLabel.toLowerCase()}`}</td>)}</tr></tbody></table></div>}</DialogContent></Dialog>
  </div>;
}
